name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LICENCEPP_OPENSSL_CROW_VESION: v1.1-cicd

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4  # Checkout the repository code
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # (Optional) Setup QEMU if needed
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # (Optional) Setup Docker Buildx if needed
      -
        name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.LICENSEPP_OPENSSL_CROW_GHCR_IO_PAT }}
      -
        name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          echo "repository_name=$(basename `git rev-parse --show-toplevel`)" >> "$GITHUB_ENV"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .  # Docker context (path to Dockerfile and build context)
          file: ./Dockerfile  # Path to Dockerfile (if not in the root)
          push: true  # Push the built image to a registry
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.repository_name }}:${{ env.branch }}-${{ env.sha_short }}
            ghcr.io/${{ github.actor }}/${{ env.repository_name }}:latest
            ghcr.io/${{ github.actor }}/${{ env.repository_name }}:${{ env.LICENCEPP_OPENSSL_CROW_VESION }}
